apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-deployment
  labels:
    app:  nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app:  nginx-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginx-deployment
        image:  nginx:alpine
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 10m 
            memory: 10Mi  
        ports:
        - containerPort:  80
          