apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  containers:
  - name: nginx-app
    image: nginx:alpine
    resources:
      limits:
        cpu: 10m
        memory: 10Mi
    ports:
    - containerPort:  80
      