apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-service
  labels:
    app:  service-nginx
spec:
  selector:
    matchLabels:
      app: service-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app:  service-nginx
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  deployment-nginx
        image:  nginx:alpine
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 10m 
            memory: 10Mi  
        ports:
        - containerPort:  80
        livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
        readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            